config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'registrations'
  }

  get     '/companies/new'    => 'companies#new',     :as => 'new_company'
  get     '/companies/:page'  => 'companies#index',   :as => 'companies'
  post    '/companies'        => 'companies#create',  :as => 'create_company'
  get     '/company/:id/edit' => 'companies#edit',    :as => 'edit_company'
  put     '/company/:id'      => 'companies#update',  :as => 'update_company'
  delete  '/company/:id'      => 'companies#destroy', :as => 'destroy_company'

  resources :invoices

  authenticated :user do
    devise_scope :user do
      root to: 'home#index'
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: 'static#index', :as => 'static_index'
    end
  end

  get  'home/index'    => 'home#index',              as: :home_index
  get  'user/company'  => 'home#new_company',        as: :new_user_company
  post 'user/company'  => 'home#create_company',     as: :create_user_company
  get  'home/edit'     => 'home#edit_company',       as: :edit_user_company
  get  'home/update'   => 'home#update_company',     as: :update_user_company

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :issued_by_company, :class_name => 'Company', :foreign_key => 'issued_by_company_id'
  belongs_to :issued_to_company, :class_name => 'Company', :foreign_key => 'issued_to_company_id'
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices/1
  # GET /invoices/1.json
  def index
    #TODO: Add guards for pages
    @page = params[:page].to_i
    if @page < 1
      @page = 1
    elsif @page > current_user.company.get_number_of_invoice_pages
      @page = current_user.company.get_number_of_invoice_pages
    end
    respond_to do |format|
      format.js
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(create_invoice_params)
    @invoice.save
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:number, :issued_by_company_id, :issued_to_company_id, :date_of_issue, :currency, :draft, :expiration_date)
    end

    def create_invoice_params
      params.require(:invoice).permit(:number, :issued_by_company_id, :issued_to_company_id, :date_of_issue, :currency, :draft, :expiration_date)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :issued_by_company_id %><br>
    <%= f.text_field :issued_by_company_id %>
  </div>
  <div class="field">
    <%= f.label :issued_to_company_id %><br>
    <%= f.text_field :issued_to_company_id %>
  </div>
  <div class="field">
    <%= f.label :date_of_issue %><br>
    <%= f.date_select :date_of_issue %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :draft %><br>
    <%= f.check_box :draft %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br>
    <%= f.date_select :expiration_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/_index.html.erb
<div class="panel">
  <%= link_to 'Add new invoice', new_invoice_path, :class => 'btn btn-success', :remote => true %>
  </br>
  <table id="invoices-table" class="table table-hover">
    <thead>
      <tr class="row">
        <th class="col-md-1">Ref. No</th>
        <th class="col-md-3">Issued to</th>
        <th class="col-md-2">Date of issue</th>
        <th class="col-md-1">Status</th>
        <th class="col-md-3">Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |invoice| %>
      <tr class="row">
        <td class="col-md-1 center-aligned"><%= link_to invoice.number, edit_invoice_path(invoice.id) %></td>
        <td class="col-md-4 center-aligned"><%= invoice.issued_to_company.name %></td>
        <td class="col-md-2 center-aligned"><%= invoice.date_of_issue %></td>
        <td class="col-md-1 center-aligned"></td>
        <td class="col-md-4 right-aligned"><%= %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'invoices/pagination', :current_page => 1 %>

app/views/invoices/_new.html.erb
<div class="panel">
  <%= form_for(@invoice, :html => {:class => 'form-horizontal'}, :url => invoices_path, :remote => true) do |f| %>
    <legend>Information about the new invoice</legend>
    <%= f.hidden_field :issued_by_company_id, :value => current_user.company.id %>
    <%= f.hidden_field :currency, :value => "USD" %>
    <%= f.hidden_field :draft, :value => true %>
    <div class="form-group">
      <%= f.label :number, 'Reference number:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :number, :autofocus => true, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :issued_to, 'Client:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= collection_select(:invoice, :issued_to_company_id, current_user.company.clients, :id, :name, {},
            html_options = {:class => "form-control"}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :expiration_date, 'Due date:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.select :expiration_date,  options_for_select(
        [
          ["Due on receipt", Date.today],
          ["7 days",  Date.today + 1.week],
          ["14 days", Date.today + 2.week],
          ["30 days", Date.today + 1.month],
          ["60 days", Date.today + 2.month]
        ]), {}, {:class => 'form-control'} %>
      </div>
    </div>
    <%= f.hidden_field :date_of_issue, :value => Date.today %>
    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <%= f.button "Create invoice", :class => 'btn btn-success' %>
        <%= f.button "Cancel", :id => 'invoice-cancel', :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/invoices/_pagination.html.erb
<div id="invoices-pagination" class="pagination-centered">
  <ul class="pagination">
    <li>
      <%= link_to '«', invoices_path(current_page-1), remote: true %>
    </li>
    <% (1..current_user.company.get_number_of_invoice_pages).each do |i| %>
      <% if current_page == i %>
      <li class="active">
        <%= link_to i, invoices_path(i), remote: true %>
      </li>
      <% else %>
      <li>
        <%= link_to i, invoices_path(i), remote: true %>
      </li>
      <% end %>
    <% end %>
    <li>
      <%= link_to '»', invoices_path(current_page+1), remote: true %>
    </li>
  </ul>
</div>

app/views/invoices/create.js.erb
<% if @invoice.id != nil %>
  window.location.href = '<%= edit_invoice_path(:id => @invoice.id) %>'
<% else %>
  <%= render 'layouts/alert', :alert => "Unable to create an invoice." %>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', home_index_path %>

app/views/invoices/new.js.erb
$('#invoice-details div').replaceWith('<%=j render 'invoices/new', :invoice => @invoice %>');
$('#invoice-details-li').tab('show');
$("#invoice-cancel").click( function(event) {
  event.preventDefault();
  $('#invoices-li').tab('show');
});

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @invoice.number %>
</p>

<p>
  <strong>Issued by company:</strong>
  <%= @invoice.issued_by_company %>
</p>

<p>
  <strong>Issued to company:</strong>
  <%= @invoice.issued_to_company %>
</p>

<p>
  <strong>Date of issue:</strong>
  <%= @invoice.date_of_issue %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @invoice.currency %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @invoice.draft %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @invoice.expiration_date %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', home_index_path %>