config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'registrations'
  }

  get     '/companies/new'    => 'companies#new',     :as => 'new_company'
  get     '/companies/:page'  => 'companies#index',   :as => 'companies'
  post    '/companies'        => 'companies#create',  :as => 'create_company'
  get     '/company/:id/edit' => 'companies#edit',    :as => 'edit_company'
  put     '/company/:id'      => 'companies#update',  :as => 'update_company'
  delete  '/company/:id'      => 'companies#destroy', :as => 'destroy_company'

  resources :invoices

  authenticated :user do
    devise_scope :user do
      root to: 'home#index'
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: 'static#index', :as => 'static_index'
    end
  end

  get  'home/index'    => 'home#index',              as: :home_index
  get  'user/company'  => 'home#new_company',        as: :new_user_company
  post 'user/company'  => 'home#create_company',     as: :create_user_company
  get  'home/edit'     => 'home#edit_company',       as: :edit_user_company
  get  'home/update'   => 'home#update_company',     as: :update_user_company

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @invoices = current_user.company.get_invoices_by_page(1)
    @clients  = current_user.company.get_clients_by_page(1)
  end

  # used for creating a company, after signing up
  # GET /company
  def new_company
    @company = Company.new
  end

  # used for creating a company, after signing up
  def create_company
    @company = Company.new(company_params)
    @company.user = current_user
    if @company.save
      redirect_to root_path
    else
      render :new_company
    end
  end

  def edit_company
    @company = current_user.company
  end

  def update_company
  end

  private
  def company_params
    params.require(:company).permit(:name, :address, :city, :country, :phone)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_edit_company.html.erb
<div class="panel">
  <%= form_for(@company, :html => {:class => 'form-horizontal', :multipart => true}, :url => update_user_company_path, :remote => true) do |f| %>
    <legend>Information about your company</legend>
    <%= f.hidden_field :id, :value => @company.id %>
    <div class="form-group">
      <%= f.label :name, 'Company name:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, :placeholder => 'e.g. Acme Corp.', :autofocus => true, :class => 'form-control', :value => company.name %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, 'Company address:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :address, :placeholder => 'e.g. 100 1st Str.', :class => 'form-control', :value => company.address %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city, 'City:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :city, :placeholder=> 'e.g. New York', :class => 'form-control', :value => company.city %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :country, 'Country:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :country, :class => 'form-control', :value => company.country %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :logo, :class => 'col-md-3 control-label' %> 
      <div class="col-md-9">
        <%= f.file_field :logo %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <%= f.submit 'Save', :class => 'btn btn-success' %>
        <%= f.button 'Cancel', :id => 'company-settings-cancel', :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/edit_company.js.erb
$('#company-settings div').replaceWith('<%=j render 'home/edit_company', :company => @company %>');
$('#company-settings-li').tab('show');
$("#company-settings-cancel").click( function(event) {
  event.preventDefault();
  $('#invoices-li').tab('show');
});

app/views/home/index.html.erb
<div class="row logo-row">
  <div class="col-md-2">
    <a class="logo">invoicerio</a>
  </div>
  <div class="col-md-8" id="alert">
  </div>
  <div class="col-md-2 text-right">
    <div class="btn-group">
      <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"><%= current_user.company.name %> <b class="caret"></b></button>
      <ul class="dropdown-menu pull-right">
        <li><%= link_to 'Account settings', edit_user_registration_path, :remote => true %></li>
        <li><%= link_to 'Company settings', edit_user_company_path, :remote => true %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-2 left-panel">
    <h3>
      <ul class="nav-menu-ul">
        <li class="active"><a href="#invoices" id="invoices-li" data-toggle="tab">Invoices</a></li>
        <li><a href="#clients" id="clients-li" data-toggle="tab">Clients</a></li>
        <li><a href="#company-details" data-toggle="tab" id="company-details-li" class="hide"></a></li>
        <li><a href="#invoice-details" data-toggle="tab" id="invoice-details-li" class="hide"></a></li>
        <li><a href="#account-settings" data-toggle="tab" id="account-settings-li" class="hide"></a></li>
        <li><a href="#company-settings" data-toggle="tab" id="company-settings-li" class="hide"></a></li>
      </ul>
    </h3>
  </div>
  <div class="col-md-10 tab-content right-panel">
    <div id="invoices" class="tab-pane fade active in">
      <%= render 'invoices/index' %>
    </div>
    <div id="clients" class="tab-pane fade">
      <%= render 'companies/index' %>
    </div>
    <div id="company-details" class="tab-pane fade">
      <div></div>
    </div>
    <div id="invoice-details" class="tab-pane fade">
      <div></div>
    </div>
    <div id="account-settings" class="tab-pane fade">
      <div></div>
    </div>
    <div id="company-settings" class="tab-pane fade">
      <div></div>
    </div>
  </div>
</div>

app/views/home/new_company.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="col-md-offset-3 col-md-9">
    <h2>Please fill in the data for your company.</h2>
  </div>
  <%= form_for(@company, :html => {:class => 'form-horizontal'}, :url => create_user_company_path) do |f| %>
    <div class="form-group">
      <%= f.label :name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :address, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :city, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :country, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :country, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :phone, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :phone, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-9">
        <%= f.submit "Create my company", :class => 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/update_company.js.erb
<%= render 'layouts/alert', :alert => "You've changed information for your company succesfully." %>
$('#invoices-li').tab('show');