config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'registrations'
  }

  get     '/companies/new'    => 'companies#new',     :as => 'new_company'
  get     '/companies/:page'  => 'companies#index',   :as => 'companies'
  post    '/companies'        => 'companies#create',  :as => 'create_company'
  get     '/company/:id/edit' => 'companies#edit',    :as => 'edit_company'
  put     '/company/:id'      => 'companies#update',  :as => 'update_company'
  delete  '/company/:id'      => 'companies#destroy', :as => 'destroy_company'

  resources :invoices

  authenticated :user do
    devise_scope :user do
      root to: 'home#index'
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: 'static#index', :as => 'static_index'
    end
  end

  get  'home/index'    => 'home#index',              as: :home_index
  get  'user/company'  => 'home#new_company',        as: :new_user_company
  post 'user/company'  => 'home#create_company',     as: :create_user_company
  get  'home/edit'     => 'home#edit_company',       as: :edit_user_company
  get  'home/update'   => 'home#update_company',     as: :update_user_company

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_one :user, inverse_of: :company

  has_many :issued_invoices,    :class_name => 'Invoice', :foreign_key => 'issued_by_company_id'
  has_many :received_invoices,  :class_name => 'Invoice', :foreign_key => 'issued_to_company_id'

  has_many :client_companies, :class_name => 'ClientCompany', :foreign_key =>'company_id'
  has_many :clients, :through => :client_companies

  def get_invoices_by_page(page)
    # To get the first page, start from index 0
    page_offset = (page-1)*10
    self.issued_invoices.limit(10).offset(page_offset)
  end

   def get_number_of_invoice_pages
    count = (self.issued_invoices.count.to_f / 10).ceil
    if count == 0
      count = 1
    end
    return count
  end

  def get_clients_by_page(page)
    # To get the first page, start from index 0
    page_offset = (page-1)*10
    self.clients.limit(10).offset(page_offset)
  end

  def get_number_of_client_pages
    count = (self.clients.count.to_f / 10).ceil
    if count == 0
      count = 1
    end
    return count
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @page = params[:page].to_i
    if @page < 1
      @page = 1
    elsif @page > current_user.company.get_number_of_client_pages
      @page = current_user.company.get_number_of_client_pages
    end
    respond_to do |format|
      format.js
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    if @company.save
      ClientCompany.create(company:current_user.company, client:@company)
      @clients  = current_user.company.get_clients_by_page(1)
    else
      render json: @company.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    if @company != nil
      current_user.company.clients.delete(@company)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :address, :city, :country, :phone, :logo_link)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_edit.html.erb
<div class="panel">
  <%= form_for(@company, :html => {:class => 'form-horizontal'}, :url => update_company_path, :remote => true) do |f| %>
    <legend>Information about the company</legend>
    <%= f.hidden_field :id, :value => @company.id %>
    <div class="form-group">
      <%= f.label :name, 'Company name:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, :placeholder => 'e.g. Acme Corp.', :autofocus => true, :class => 'form-control', :value => company.name %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, 'Company address:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :address, :placeholder => 'e.g. 100 1st Str.', :class => 'form-control', :value => company.address %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city, 'City:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :city, :placeholder=> 'e.g. New York', :class => 'form-control', :value => company.city %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :country, 'Country:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :country, :class => 'form-control', :value => company.country %>
      </div>
    </div>
    <div class="form-group">
      <%#= f.label :email, 'Company email:', :class => 'control-label' %>
      <div class="col-md-9">
        <%#= f.email_field :email, :placeholder => 'e.g. mail@example.com', :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <%= f.submit 'Save', :class => 'btn btn-success' %>
        <%= link_to  'Delete', destroy_company_path(@company.id), :class => 'btn btn-danger', :method => 'delete', :remote => true %>
        <%= f.button 'Cancel', :id => 'company-cancel', :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/_index.html.erb
<div class="panel">
  <%= link_to 'Add new client', new_company_path, :class => 'btn btn-success', :remote => true %>
  </br>
  <%= render 'companies/table', :clients => @clients %>
</div>
<%= render 'companies/pagination', :current_page => 1 %>

app/views/companies/_new.html.erb
<div class="panel">
  <%= form_for(@company, :html => {:class => 'form-horizontal'}, :url => create_company_path, :remote => true) do |f| %>
    <legend>Information about the company</legend>
    <div class="form-group">
      <%= f.label :name, 'Company name:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, :placeholder => 'e.g. Acme Corp.', :autofocus => true, :class => 'form-control', :value => company.name %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, 'Company address:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :address, :placeholder => 'e.g. 100 1st Str.', :class => 'form-control', :value => company.address %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city, 'City:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :city, :placeholder=> 'e.g. New York', :class => 'form-control', :value => company.city %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :country, 'Country:', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :country, :class => 'form-control', :value => company.country %>
      </div>
    </div>
    <div class="form-group">
      <%#= f.label :email, 'Company email:', :class => 'control-label' %>
      <div class="col-md-9">
        <%#= f.email_field :email, :placeholder => 'e.g. mail@example.com', :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <%= f.submit 'Create company', :class => 'btn btn-success' %>
        <%= f.button 'Cancel', :id => 'company-cancel', :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/_pagination.html.erb
<div id="clients-pagination" class="pagination-centered">
  <ul class="pagination">
    <li>
      <%= link_to '«', companies_path(current_page-1), remote: true %>
    </li>
    <% (1..current_user.company.get_number_of_client_pages).each do |i| %>
    <% if current_page == i %>
    <li class="active">
    <%= link_to i, companies_path(i), remote: true %>
    </li>
    <% else %>
    <li>
      <%= link_to i, companies_path(i), remote: true %>
    </li>
    <% end %>
    <% end %>
    <li>
      <%= link_to '»', companies_path(current_page+1), remote: true %>
    </li>
  </ul>
</div>

app/views/companies/_table.html.erb
<table id="clients-table" class="table table-hover client-table">
  <thead>
    <tr class="row">
      <th class="col-md-4">Client</th>
      <th class="col-md-4 text-center">Address</th>
      <th class="col-md-4 text-center">City</th>
    </tr>
  </thead>
  <tbody>
    <% clients.each do |p| %>
    <tr class="row">
      <td class="col-md-4"><%= link_to p.name, edit_company_path(p.id), remote: true %></td>
      <td class="col-md-4 text-center"><%= p.address %></td>
      <td class="col-md-4 text-center"><%= p.city %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/create.js.erb
$('#clients-table').replaceWith('<%=j render 'companies/table', :clients => @clients %>');
$('#clients-pagination').replaceWith('<%=j render 'companies/pagination', :current_page => 1 %>');
<%= render 'layouts/alert', :alert => "You've added #{@company.name} to your clients" %>
$('#clients-li').tab('show');

app/views/companies/destroy.js.erb
$('#clients-table').replaceWith('<%=j render 'companies/table', :clients => current_user.company.get_clients_by_page(1) %>');
$('#clients-pagination').replaceWith('<%=j render 'companies/pagination', :current_page => 1 %>');
<%= render 'layouts/alert', :alert => "You've removed #{@company.name} as your client." %>
$('#clients-li').tab('show');

app/views/companies/edit.js.erb
$('#company-details div').replaceWith('<%=j render 'companies/edit', :company => @company %>');
$('#company-details-li').tab('show');
$("#company-cancel").click( function(event) {
  event.preventDefault();
  $('#clients-li').tab('show');
});

app/views/companies/index.js.erb
$('#clients-table').replaceWith('<%=j render 'companies/table', :clients => current_user.company.get_clients_by_page(@page) %>');
$('#clients-pagination').replaceWith('<%=j render 'companies/pagination', :current_page => @page %>');

app/views/companies/new.js.erb
$('#company-details div').replaceWith('<%=j render 'companies/new', :company => @company %>');
$('#company-details-li').tab('show');
$("#company-cancel").click( function(event) {
  event.preventDefault();
  $('#clients-li').tab('show');
});